name: queries
version: 0.1.14
description: Enumerable collections for Dart language (inspired by Microsoft LINQ).
homepage: https://github.com/mezoni/queries
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  function_types: '>=0.0.2 <=1.0.0'
dev_dependencies:  
  test: ^1.5.3  
